FROM alpine:3

LABEL author="Fadhil Awalia Kusuma"
LABEL nim="11231023" matkul="Sistem Paralel dan Terdistribusi"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"
